# Generated by Django 3.1.4 on 2020-12-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('polls', '0002_image_mem'),
    ]

    operations = [
        migrations.AddField(
            model_name='mem',
            name='path',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
